### ISSUE TITLE
<span> elements

### ISSUE THREAD

**Issue by aubreywullschleger** [kkrishnak/f1-3-c2p1-colmar-academy#1]
Important for errors! Heading (`<h1>` - `<h6>`) and `<p>` elements are not allowed to be nested inside of `<span>` elements.  `<span>` elements can only have phrasing content nested inside.  See here for more info about what phrasing elements are: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content and more about the `<span>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span

Example: https://github.com/kkrishnak/f1-3-c2p1-colmar-academy/blob/master/Capstone%20Project%20-%20Colmar%20Academy/index.html#L127-L131

**Comment by kkrishnak** [comment]
Thanks for the reviewing the project. I will look into it.
