### ISSUE TITLE
Closing elements

### ISSUE THREAD

**Issue by aubreywullschleger** [kkrishnak/f1-3-c2p1-colmar-academy#2]
Subtlety for errors!  Make sure you are closing your elements correctly.

For example, in your HTML, line 75 should be: `</span>` to close the opening `<span>` tag from line 70,  line 157 is missing the closing `</p>`, and line 197 should be: `</span>`.

**Comment by kkrishnak** [comment]
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Colmar Academy</title>
    <link href="resources/css/reset.css" rel="stylesheet" type="text/css" />
    <link href="resources/css/style.css" rel="stylesheet" type="text/css" />

    
    <link href="https://fonts.googleapis.com/css?family=Palanquin+Dark:600,700|Palanquin:300,400,500|Sarala:400,700" rel="stylesheet">

    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
    
    <div class="header-desktop">
        <div class="logo">
            <img src="resources/images/ic-logo.svg" /><span id="colmar">COLMAR</span><span id="academy">ACADEMY</span>
        </div>
        
        <nav>
            <span class="desktop"><a href="#">On Campus</a></span>
            <span class="desktop"><a href="#">Online</a></span>
            <span class="desktop"><a href="#">For Companies</a></span>
            <span class="desktop"><a href="#">Sign in</a></span>
        </nav>
    </div>
    

    
    <div class="header-mobile">
        <div class="mobile">
            <a href="#"><img src="resources/images/ic-logo.svg" /></a>
        </div>
        <div class="mobile">
            <a href="#"><img src="resources/images/ic-on-campus.svg"></a>
        </div>
        <div class="mobile">
            <a href="#"><img src="resources/images/ic-online.svg"></a>
        </div>
        <div class="mobile">
            <a href="#"><img src="resources/images/ic-login.svg"></a>
        </div>
    </div>
    


    
    <div class="intro">
        <div class="intro-img">
            <img src="resources/images/banner.jpg" />
        </div>
        
        <div class="intro-content">
            <h1>Learn something new everyday.</h1>
            <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3>
            <a href="#" class="button">Start here</a>
        </div>
        
    </div>
    

    
    <div class="info">
        <div class="info-main">
            <img src="resources/images/information-main.jpg" />
            <span>
            <h1>It doesn't hurt to keep practicing</h1>
            <p>"Curabitur nec lacinia libero, a interdum ex. Aliquam turpis urna, vehicula non malesuada id, scelerisque luctus risus. Mauris fringilla bibendum nisi, sit amet efficitur orci dictum interdum. Pellentesque a fermentum erat, ac accumsan dolor."</p>
            <br />
            <p id="attrib">Emanuel, Sr. Strategist at Hiring.com</p>
            </span>
        </div> 
        <div class="info-cards">
            <div class="info-content"> 
              <a href="#">
                <img class="img-desktop" src="resources/images/information-orientation.jpg" />
                <img class="img-mobile" src="resources/images/information-orientation-mobile.jpg" />
                <span class="text">
                  <h3>Orientation Date</h3>
                  <p>Tue 10/11 &amp; Wed 10/12: 8am-3pm</p>
                  <span id="display-control">Read more</span>
            </span>
            </a>
        </div>
        
        <div class="info-content">
            <a href="#">
                <img class="img-desktop" src="resources/images/information-campus.jpg" />
                <img class="img-mobile" src="resources/images/information-campus-mobile.jpg" />
                <span class="text">
                  <h3>Our campus</h3>
                  <p>Find which campus is close by you.</p>
                  <span id="display-control">Read more</span>
                </span>
            </a>
        </div>  
        <div class="info-content">
            <a href="#">
                <img class="img-desktop" src="resources/images/information-guest-lecture.jpg" />
                <img class="img-mobile" src="resources/images/information-guest-lecture-mobile.jpg" />
                <span class="text">
                  <h3>Our guest lecture</h3>
                  <p>Join a keynote with Oliver Sack about music in medical treatment.</p>
                  <span id="display-control">Read more</span>
                </span>
            </a>
        </div>
        
    </div>
    
    </div>
    

    
    <div class="curriculum">
        <div class="curr-title">
            <h1>Start learning</h1>
        </div>
        
        <div class="curr-cards">
            <div class="course">
                <img src="resources/images/course-software.jpg">
                <span class="course-text">
                <h3>Software engineering</h3>
                <h5>COURSES</h5>
                <p>Web development, Mobile Development, iOT, APIs</p>
              </span>
            </div>
            
            <div class="course">
                <img src="resources/images/course-computer-art.jpg">
                <span class="course-text">
                <h3>Computer art</h3>
                <h5>COURSES</h5>
                <p>Imaging & Design, Web Design, Motion Graphics & Visual Effects, Computer Animation</p>
              </span>
            </div>
            
            <div class="course">
                <img src="resources/images/course-design.jpg">
                <span class="course-text">
                <h3>Design</h3>
                <h5>COURSES</h5>
                <p>User Experience Design, User Research, Visual Design</p>
              </span>
            </div>
            
            <div class="course">
                <img src="resources/images/course-data.jpg">
                <span class="course-text">
                  <h3>Data</h3>
                  <h5>COURSES</h5>
                  <p>Data Science, Big Data, SQL, Data Visualization</p>
                </span>
            </div>
            
            <div class="course">
                <img src="resources/images/course-business.jpg">
                <span class="course-text">
                <h3>Business</h3>
                <h5>COURSES</h5>
                <p>Product Development, Business Development, Startup</p>
              </span>
            </div>
            
            <div class="course">
                <img src="resources/images/course-marketing.jpg">
                <span class="course-text">
                <h3>Marketing</h3>
                <h5>COURSES</h5>
                <p>Analytics, Content Marketing, Mobile Marketing</p>
              </span>
            </div>
            
        </div>
        
    </div>
    

    
    <div class="thesis">
        <div class="thesis-title">
            <h1>Thesis Exhibits</h1>
        </div>
        
        <div class="thesis-vid">
            <video width="700" controls>
              <source src="resources/videos/thesis.mp4" type="video/mp4">Your browser does not support the video tag.
              </video>
            <span>
                <h3>Reimagine urban</h3>
                <p>"Curabitur nec lacinia libero, a interdum ex. Aliquam turpis urna, vehicula non malesuada id, scelerisque luctus risus. Mauris fringilla bibendum nisi, sit amet efficitur orci dictum interdum. Pellentesque a fermentum erat, ac accumsan dolor."</p>
              </span>
        </div> 
        <div class="thesis-cards">
            <div class="thesis-feature">
                <img src="resources/images/thesis-fisma.jpg">
                <span class="thesis-text">
                  <h3>Fisma: Design</h3>
                  <p>Designer showcase of new prototype product</p>
                </span>
        </div>
        
        <div class="thesis-feature">
            <img src="resources/images/thesis-now-and-then.jpg">
            <span class="thesis-text">
                  <h3>Now and then</h3>
                  <p>Research study about New York</p>
                </span>
        </div>
        
    </div>
    
    </div>
    

    
    
    <footer>
        <span>&copy; 2016 Colmar Academy. All rights reserved.</span>
        <span class="links">
            <a href="#">Terms</a>
            <a href="#">Privacy</a>
          </span>
    </footer>
    
</body>

</html>

**Comment by kkrishnak** [comment]
Thanks for the reviewing the project. I made the changes accordingly.
