### ISSUE TITLE
Id attributes

### ISSUE THREAD

**Issue by aubreywullschleger** [kkrishnak/f1-3-c2p1-colmar-academy#3]
Important for errors! When we use `id` attributes in HTML we need to make sure those `id` attributes are unique to the entire document per best practices (see here: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id ) meaning that there should be no `id` attributes that have the same value. You would want to use `class="display-control"` if you needed to repeat an identifier instead of using `id="display-control"` multiple times (and change your selectors in CSS to account for this change).

Example: https://github.com/kkrishnak/f1-3-c2p1-colmar-academy/blob/master/Capstone%20Project%20-%20Colmar%20Academy/index.html#L85
https://github.com/kkrishnak/f1-3-c2p1-colmar-academy/blob/master/Capstone%20Project%20-%20Colmar%20Academy/index.html#L108

**Comment by kkrishnak** [comment]
Thanks for the reviewing the project. I will work on this,
