### ISSUE TITLE
Locally stored media

### ISSUE THREAD

**Issue by aubreywullschleger** [kkrishnak/f1-3-c2p1-colmar-academy#4]
Great! Good job using locally stored media for your project.  This is best practice and allows your page to load faster.  Be sure to use descriptive `alt` attributes on all your `<img>` elements, like this: `<img src="resources/images/banner.jpg" alt="three people studying at picnic table" />`  as this is best practice and helps your site to be even more accessible!

Example: https://github.com/kkrishnak/f1-3-c2p1-colmar-academy/blob/master/Capstone%20Project%20-%20Colmar%20Academy/index.html#L54

**Comment by kkrishnak** [comment]
Thanks for the reviewing the project. I will work on it.
