### ISSUE TITLE
Responsive concepts

### ISSUE THREAD

**Issue by aubreywullschleger** [kkrishnak/f1-3-c2p1-colmar-academy#5]
Great! Nice job using flex-box and media queries for a responsive page. Be sure to use group selectors for repeated styles like `font-family: 'Palanquin Dark', sans-serif;` and `display: flex;`, and use one media query per screen width to make your CSS more concise.

**Comment by kkrishnak** [comment]
Thanks for the reviewing the project. Thanks for giving the feedback.
