### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [kkrishnak/f1-3-c2p1-colmar-academy#6]
Grade: Meets expectations

Summary:
Good job with the capstone! I love your organized HTML, that you used some semantic HTML elements like `<nav>` and `<footer>`, your use of locally stored media, and that your page is responsive.

A few things to work on would be: 1. nesting your elements correctly, 2. making sure all of your elements are closed, 3. not repeating `id` attributes, 4. using descriptive `alt` attributes for your `<img>` elements, and 5. making your CSS even more concise by using group selectors for repeated styles and a single media query per page width.

Next, after implementing my suggestions, I challenge you to build more pages for this site.  What does a sign in page look like? What about a course page?  Building these extra pages will add some complexity and is a challenge I think you are ready for based on your work here!

**Comment by kkrishnak** [comment]
Thanks for the reviewing the project. Thanks for the feedback. I will work on it. Thanks for the support.
